/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mcs_crypto_RawRC4 */

#ifndef _Included_com_mcs_crypto_RawRC4
#define _Included_com_mcs_crypto_RawRC4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mcs_crypto_RawRC4
 * Method:    RawNew
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_mcs_crypto_RawRC4_RawNew
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_mcs_crypto_RawRC4
 * Method:    RawXORStream
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_mcs_crypto_RawRC4_RawXORStream
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_mcs_crypto_RawRC4
 * Method:    RawDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mcs_crypto_RawRC4_RawDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_mcs_crypto_RawRC4
 * Method:    RawReset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mcs_crypto_RawRC4_RawReset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
